on:
  push:
    branches:
      - main

  pull_request:
      types: [opened, synchronize, reopened]

name: Example Workflow

jobs:
  linter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Example
      run: |
        echo "Aqui você vai fazendo o que precisa"
